// Package dockershim writes a small POSIX shell script under a user-chosen
// path that maps the most common docker(1) subcommands to their Apple
// `container` CLI equivalents. With the script on PATH (and shadowing any
// previously-installed docker binary), familiar invocations like
// `docker ps`, `docker images`, `docker pull <ref>` "just work" against
// Apple containers without users having to relearn the verb shape.
//
// This is a best-effort compatibility shim, not a drop-in replacement.
// docker has many flags Apple's CLI doesn't expose and vice versa; the
// shim translates command shape only and forwards remaining argv as-is.
package dockershim

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Sentinel marks files written by this package so Uninstall can refuse
// to delete an unrelated docker binary the user might have on PATH.
const Sentinel = "c9s docker -> apple container"

// Script is the embedded bash shim. It maps a small but high-traffic set
// of docker verbs to their `container` equivalents and falls through to
// `container "$@"` for everything else, so unhandled subcommands at
// least surface a clean Apple-CLI error instead of a confusing wrapper
// failure.
const Script = `#!/usr/bin/env bash
# ` + Sentinel + ` compatibility shim.
# Generated by c9s install-docker-shim. DO NOT EDIT MANUALLY — re-run the
# subcommand to refresh.
#
# Translates the most common docker(1) verbs to their Apple ` + "`container`" + ` CLI
# equivalents. Unknown verbs fall through unchanged. Run with 'docker --help'
# to see Apple's help text (it shadows docker so this script is now docker).
set -euo pipefail

# Resolve the underlying Apple binary. Honour CONTAINER_BIN so users on
# unusual installs (or doing ` + "`brew`" + ` work) can override.
BIN="${CONTAINER_BIN:-container}"
if ! command -v "$BIN" >/dev/null 2>&1; then
  echo "c9s docker shim: '$BIN' not found on PATH (set CONTAINER_BIN to override)" >&2
  exit 127
fi

if [[ $# -eq 0 ]]; then
  exec "$BIN"
fi

verb="$1"; shift
case "$verb" in
  # Lifecycle ─ direct passthroughs.
  run|start|stop|restart|kill|exec|inspect|logs|build|create|delete)
    exec "$BIN" "$verb" "$@" ;;

  # docker rm <id>  →  container delete <id>
  rm)
    exec "$BIN" delete "$@" ;;

  # docker ps [-a]  →  container list [--all]
  ps)
    args=()
    for a in "$@"; do
      case "$a" in
        -a|--all) args+=(--all) ;;
        *)        args+=("$a") ;;
      esac
    done
    exec "$BIN" list "${args[@]+"${args[@]}"}" ;;

  # docker images  →  container image list
  images)
    exec "$BIN" image list "$@" ;;

  # docker rmi <id>  →  container image delete <id>
  rmi)
    exec "$BIN" image delete "$@" ;;

  # docker pull / push / tag  →  container image <verb>
  pull|push|tag)
    exec "$BIN" image "$verb" "$@" ;;

  # docker volume / network namespace passthroughs map ls→list.
  volume|network)
    sub="${1:-}"; shift || true
    case "$sub" in
      ls)
        exec "$BIN" "$verb" list "$@" ;;
      "")
        # Bare 'docker volume' / 'docker network' should defer to
        # Apple's CLI for help/usage rather than passing it an
        # empty positional that confuses the parser.
        exec "$BIN" "$verb" ;;
      *)
        exec "$BIN" "$verb" "$sub" "$@" ;;
    esac ;;

  # docker login / logout → container registry login / logout
  login)
    exec "$BIN" registry login "$@" ;;
  logout)
    exec "$BIN" registry logout "$@" ;;

  # docker version → container --version (closest analogue Apple exposes)
  version)
    exec "$BIN" --version ;;
  # docker info / system → container system <args>: 'info' really means
  # daemon/system state, so we route it into Apple's system namespace
  # and let it surface its own subcommand mismatch if any.
  info)
    exec "$BIN" system info "$@" ;;
  system)
    exec "$BIN" system "$@" ;;

  # Unknown verb: fall through so users see the underlying CLI's error.
  *)
    exec "$BIN" "$verb" "$@" ;;
esac
`

// DefaultPath returns ~/.local/bin/docker, which lives in many shells'
// PATH by default and doesn't require sudo.
func DefaultPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("home dir: %w", err)
	}
	return filepath.Join(home, ".local", "bin", "docker"), nil
}

// Install writes Script to path, creating parent dirs as needed and
// chmod'ing the result executable. If a file (or symlink, even broken)
// already exists at path and force is false, Install errors out so we
// don't quietly clobber a real docker binary or follow a stale symlink
// to write the script in the wrong place.
func Install(path string, force bool) error {
	if path == "" {
		return errors.New("path is empty")
	}
	// Lstat (not Stat) so a symlink — even one whose target is missing —
	// is treated as "exists, refuse". Stat would follow the link and
	// return IsNotExist for a broken link, leading WriteFile to write
	// through the link to the wrong path.
	if _, err := os.Lstat(path); err == nil && !force {
		return fmt.Errorf("%s already exists; pass --force to overwrite", path)
	} else if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("stat %s: %w", path, err)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(Script), 0o755); err != nil { //nolint:gosec // executable shim, intentional 0o755
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

// Uninstall removes the shim at path. It refuses to delete the file if
// the script doesn't carry the c9s sentinel header, so a misconfigured
// command can't accidentally delete a real docker binary.
func Uninstall(path string) error {
	if path == "" {
		return errors.New("path is empty")
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}
	header := data
	if len(header) > 256 {
		header = header[:256]
	}
	if !strings.Contains(string(header), Sentinel) {
		return fmt.Errorf("%s does not look like a c9s shim (header missing sentinel %q)", path, Sentinel)
	}
	if err := os.Remove(path); err != nil {
		return fmt.Errorf("remove %s: %w", path, err)
	}
	return nil
}
